web:
  image: swf/nginx
  ports:
    - "443:443"
   # - "80:80"
  volumes:
    - ./src:/var/www
    - ./ssl-certs/certs:/etc/ssl/certs
    - ./ssl-certs/private:/etc/ssl/private 
    - ./src/actavo.conf:/etc/nginx/sites-enabled/actavo.conf
    - ./src/scottishpower.conf:/etc/nginx/sites-enabled/scottishpower.conf
    - ./src/icl.conf:/etc/nginx/sites-enabled/icl.conf
  links:
    - phpActavo
    - phpScottishPower
    - phpIcl 

phpActavo:
  image: nmcteam/php56
  volumes:
    - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src/actavo:/var/www
  links:
    - db

phpScottishPower:
  image: nmcteam/php56
  volumes:
    - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src/scottishpower:/var/www
  links:
    - db
 
phpIcl:
  image: nmcteam/php56
  volumes:
    - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src/icl:/var/www
  links:
    - db 

db:
  image: mariadb
  volumes:
   - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=admin 
    
phpmyadmin:
   image: phpmyadmin/phpmyadmin
   restart: always 
   ports:
     - "8082:80"
   environment:
     - PMA_ARBITRARY=1 
   links: 
     - db
